In [1]:
import pandas as pd
import wbgapi as wb

In [25]:
wb.source.info()

id    name                                                                  code      concepts  lastupdated
----  --------------------------------------------------------------------  ------  ----------  -------------
1     Doing Business                                                        DBS              3  2021-08-18
2     World Development Indicators                                          WDI              3  2022-12-22
3     Worldwide Governance Indicators                                       WGI              3  2022-09-23
5     Subnational Malnutrition Database                                     SNM              3  2016-03-21
6     International Debt Statistics                                         IDS              4  2022-12-06
11    Africa Development Indicators                                         ADI              3  2013-02-22
12    Education Statistics                                                  EDS              3  2020-12-20
13    Enterprise Surveys                                                    ESY              3  2022-03-25
14    Gender Statistics                                                     GDS              3  2022-06-23
15    Global Economic Monitor                                               GEM              3  2020-07-27
16    Health Nutrition and Population Statistics                            HNP              3  2022-12-23
18    IDA Results Measurement System                                        IDA              3  2021-07-23
19    Millennium Development Goals                                          MDG              3  2018-09-19
20    Quarterly Public Sector Debt                                          PSD              3  2023-01-25
22    Quarterly External Debt Statistics SDDS                               QDS              3  2023-01-17
23    Quarterly External Debt Statistics GDDS                               QDG              3  2023-01-17
25    Jobs                                                                  JOB              3  2022-06-29
27    Global Economic Prospects                                             GEP              3  2023-01-10
28    Global Financial Inclusion                                            FDX              3  2022-10-24
29    The Atlas of Social Protection: Indicators of Resilience and Equity   GSP              3  2021-12-20
30    Exporter Dynamics Database – Indicators at Country-Year Level         ED1              3  2016-03-31
31    Country Policy and Institutional Assessment                           CPI              3  2022-09-15
32    Global Financial Development                                          GFD              3  2022-09-23
33    G20 Financial Inclusion Indicators                                    G2F              3  2019-02-27
34    Global Partnership for Education                                      GPE              3  2013-04-12
35    Sustainable Energy for All                                            SE4              3  2018-06-30
36    Statistical Capacity Indicators                                       BBS              3  2021-02-03
37    LAC Equity Lab                                                        LEL              3  2016-04-06
38    Subnational Poverty                                                   SNP              3  2015-04-27
39    Health Nutrition and Population Statistics by Wealth Quintile         HNQ              3  2022-12-13
40    Population estimates and projections                                  HPP              3  2022-12-23
41    Country Partnership Strategy for India (FY2013 - 17)                  CPS              3  2015-05-22
43    Adjusted Net Savings                                                  WAT              3  2022-09-20
45    Indonesia Database for Policy and Economic Research                   IDD              3  2022-08-11
46    Sustainable Development Goals                                         SDG              3  2022-07-22
50    Subnational Population                                                SNT              3  2017-09-21
54    Joint External Debt Hub                                               JED              3  2022-08-22
57    WDI Database Archives                                                 WDA              4  2022-11-01
58    Universal Health Coverage                                             UHC              3  2019-04-25
59    Wealth Accounts                                                       WAC              3  2021-10-27
60    Economic Fitness                                                      EFT              3  2018-04-19
61    PPPs Regulatory Quality                                               PRQ              3  2019-04-25
62    International Comparison Program (ICP) 2011                           ICP              4  2020-08-24
63    Human Capital Index                                                   HCI              3  2020-09-21
64    Worldwide Bureaucracy Indicators                                      WBI              3  2022-09-20
65    Health Equity and Financial Protection Indicators                     HPI              3  2019-11-06
66    Logistics Performance Index                                           LPI              3  2019-10-29
67    PEFA 2011                                                             PF1              4  2022-11-23
68    PEFA 2016                                                             PF6              4  2023-01-12
69    Global Financial Inclusion and Consumer Protection Survey             RFA              3  2019-06-27
70    Economic Fitness 2                                                    EF2              3  2022-07-21
71    International Comparison Program (ICP) 2005                           IC5              4  2021-09-10
73    Global Financial Inclusion and Consumer Protection Survey (Internal)  RFI              3  2019-06-27
75    Environment, Social and Governance (ESG) Data                         ESG              3  2023-01-17
76    Remittance Prices Worldwide (Sending Countries)                       RWS              3  2020-12-07
77    Remittance Prices Worldwide (Receiving Countries)                     RWR              3  2020-12-07
78    ICP 2017                                                              IC7              4  2020-10-21
79    PEFA_GRPFM                                                            GRP              4  2022-12-18
80    Gender Disaggregated Labor Database (GDLD)                            GDL              4  2020-07-25
81    International Debt Statistics: DSSI                                   DSI              4  2022-12-06
82    Global Public Procurement                                             GPP              3  2021-03-24
83    Statistical Performance Indicators (SPI)                              SPI              3  2021-04-01
84    Education Policy                                                      EDP              3  2022-07-19
85    PEFA_2021_SNG                                                         SNG              4  2022-11-03
86    Global Jobs Indicators Database (JOIN)                                JON              3  2021-09-24
87    Country Climate and Development Report (CCDR)                         CCD              3  2022-10-07
88    Food Prices for Nutrition                                             FPN              4  2022-07-05
89    Identification for Development (ID4D) Data                            ID4              3  2022-12-21
      68 elements

In [20]:
help(wb)

Help on package wbgapi:

NAME
    wbgapi

DESCRIPTION
    wbgapi provides a comprehensive interface to the World Bank's data and
    metadata API with built-in pandas integration

PACKAGE CONTENTS
    __version__
    data
    economy
    economy_coder
    economy_metadata
    income
    lending
    region
    series
    series_metadata
    source
    time
    topic
    utils

CLASSES
    builtins.Exception(builtins.BaseException)
        APIError
            APIResponseError
        URLError
    builtins.dict(builtins.object)
        Coder
    builtins.object
        Featureset
        Metadata
        MetadataCollection

    class APIError(builtins.Exception)
     |  APIError(url, msg, code=None)
     |
     |  Method resolution order:
     |      APIError
     |      builtins.Exception
     |      builtins.BaseException
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __init__(self, url, msg, code=None)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  __str__(self)
     |      Return str(self).
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Static methods inherited from builtins.Exception:
     |
     |  __new__(*args, **kwargs) from builtins.type
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.BaseException:
     |
     |  __delattr__(self, name, /)
     |      Implement delattr(self, name).
     |
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |
     |  __reduce__(...)
     |      Helper for pickle.
     |
     |  __repr__(self, /)
     |      Return repr(self).
     |
     |  __setattr__(self, name, value, /)
     |      Implement setattr(self, name, value).
     |
     |  __setstate__(...)
     |
     |  add_note(...)
     |      Exception.add_note(note) --
     |      add a note to the exception
     |
     |  with_traceback(...)
     |      Exception.with_traceback(tb) --
     |      set self.__traceback__ to tb and return self.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from builtins.BaseException:
     |
     |  __cause__
     |      exception cause
     |
     |  __context__
     |      exception context
     |
     |  __dict__
     |
     |  __suppress_context__
     |
     |  __traceback__
     |
     |  args

    class APIResponseError(APIError)
     |  APIResponseError(url, msg)
     |
     |  This error indicates that the module didn't understand the response from the API.
     |  Either it couldn't parse the JSON (the API sometimes returns XML even when JSON is
     |  requested) or it doesn't recognize the json schema
     |
     |  Method resolution order:
     |      APIResponseError
     |      APIError
     |      builtins.Exception
     |      builtins.BaseException
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __init__(self, url, msg)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from APIError:
     |
     |  __str__(self)
     |      Return str(self).
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from APIError:
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Static methods inherited from builtins.Exception:
     |
     |  __new__(*args, **kwargs) from builtins.type
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.BaseException:
     |
     |  __delattr__(self, name, /)
     |      Implement delattr(self, name).
     |
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |
     |  __reduce__(...)
     |      Helper for pickle.
     |
     |  __repr__(self, /)
     |      Return repr(self).
     |
     |  __setattr__(self, name, value, /)
     |      Implement setattr(self, name, value).
     |
     |  __setstate__(...)
     |
     |  add_note(...)
     |      Exception.add_note(note) --
     |      add a note to the exception
     |
     |  with_traceback(...)
     |      Exception.with_traceback(tb) --
     |      set self.__traceback__ to tb and return self.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from builtins.BaseException:
     |
     |  __cause__
     |      exception cause
     |
     |  __context__
     |      exception context
     |
     |  __dict__
     |
     |  __suppress_context__
     |
     |  __traceback__
     |
     |  args

    class Coder(builtins.dict)
     |  Class returned by coder if passed a list of terms
     |
     |  Method resolution order:
     |      Coder
     |      builtins.dict
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __repr__(self)
     |      Return repr(self).
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.dict:
     |
     |  __contains__(self, key, /)
     |      True if the dictionary has the specified key, else False.
     |
     |  __delitem__(self, key, /)
     |      Delete self[key].
     |
     |  __eq__(self, value, /)
     |      Return self==value.
     |
     |  __ge__(self, value, /)
     |      Return self>=value.
     |
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |
     |  __getitem__(...)
     |      x.__getitem__(y) <==> x[y]
     |
     |  __gt__(self, value, /)
     |      Return self>value.
     |
     |  __init__(self, /, *args, **kwargs)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  __ior__(self, value, /)
     |      Return self|=value.
     |
     |  __iter__(self, /)
     |      Implement iter(self).
     |
     |  __le__(self, value, /)
     |      Return self<=value.
     |
     |  __len__(self, /)
     |      Return len(self).
     |
     |  __lt__(self, value, /)
     |      Return self<value.
     |
     |  __ne__(self, value, /)
     |      Return self!=value.
     |
     |  __or__(self, value, /)
     |      Return self|value.
     |
     |  __reversed__(self, /)
     |      Return a reverse iterator over the dict keys.
     |
     |  __ror__(self, value, /)
     |      Return value|self.
     |
     |  __setitem__(self, key, value, /)
     |      Set self[key] to value.
     |
     |  __sizeof__(...)
     |      D.__sizeof__() -> size of D in memory, in bytes
     |
     |  clear(...)
     |      D.clear() -> None.  Remove all items from D.
     |
     |  copy(...)
     |      D.copy() -> a shallow copy of D
     |
     |  get(self, key, default=None, /)
     |      Return the value for key if key is in the dictionary, else default.
     |
     |  items(...)
     |      D.items() -> a set-like object providing a view on D's items
     |
     |  keys(...)
     |      D.keys() -> a set-like object providing a view on D's keys
     |
     |  pop(...)
     |      D.pop(k[,d]) -> v, remove specified key and return the corresponding value.
     |
     |      If the key is not found, return the default if given; otherwise,
     |      raise a KeyError.
     |
     |  popitem(self, /)
     |      Remove and return a (key, value) pair as a 2-tuple.
     |
     |      Pairs are returned in LIFO (last-in, first-out) order.
     |      Raises KeyError if the dict is empty.
     |
     |  setdefault(self, key, default=None, /)
     |      Insert key with a value of default if key is not in the dictionary.
     |
     |      Return the value for key if key is in the dictionary, else default.
     |
     |  update(...)
     |      D.update([E, ]**F) -> None.  Update D from dict/iterable E and F.
     |      If E is present and has a .keys() method, then does:  for k in E: D[k] = E[k]
     |      If E is present and lacks a .keys() method, then does:  for k, v in E: D[k] = v
     |      In either case, this is followed by: for k in F:  D[k] = F[k]
     |
     |  values(...)
     |      D.values() -> an object providing a view on D's values
     |
     |  ----------------------------------------------------------------------
     |  Class methods inherited from builtins.dict:
     |
     |  __class_getitem__(...) from builtins.type
     |      See PEP 585
     |
     |  fromkeys(iterable, value=None, /) from builtins.type
     |      Create a new dictionary with keys from iterable and values set to value.
     |
     |  ----------------------------------------------------------------------
     |  Static methods inherited from builtins.dict:
     |
     |  __new__(*args, **kwargs) from builtins.type
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from builtins.dict:
     |
     |  __hash__ = None

    class Featureset(builtins.object)
     |  Featureset(items, columns=None)
     |
     |  Methods defined here:
     |
     |  __init__(self, items, columns=None)
     |      can be initialized with any iterable
     |
     |  __repr__(self)
     |      Return repr(self).
     |
     |  table(self)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)

    class Metadata(builtins.object)
     |  Metadata(concept, id, name)
     |
     |  Methods defined here:
     |
     |  __init__(self, concept, id, name)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  __repr__(self)
     |      Return repr(self).
     |
     |  repr(self, q=None, padding=None)
     |      Same as __repr__ but includes formatting options
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)

    class MetadataCollection(builtins.object)
     |  MetadataCollection(brief=False, padding=80, q=None)
     |
     |  Methods defined here:
     |
     |  __init__(self, brief=False, padding=80, q=None)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  __repr__(self)
     |      Return repr(self).
     |
     |  append(self, meta)
     |      Append a Metadata object to our store
     |
     |  brief_table(self, tablefmt)
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)

    class URLError(builtins.Exception)
     |  Method resolution order:
     |      URLError
     |      builtins.Exception
     |      builtins.BaseException
     |      builtins.object
     |
     |  Data descriptors defined here:
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.Exception:
     |
     |  __init__(self, /, *args, **kwargs)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Static methods inherited from builtins.Exception:
     |
     |  __new__(*args, **kwargs) from builtins.type
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.BaseException:
     |
     |  __delattr__(self, name, /)
     |      Implement delattr(self, name).
     |
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |
     |  __reduce__(...)
     |      Helper for pickle.
     |
     |  __repr__(self, /)
     |      Return repr(self).
     |
     |  __setattr__(self, name, value, /)
     |      Implement setattr(self, name, value).
     |
     |  __setstate__(...)
     |
     |  __str__(self, /)
     |      Return str(self).
     |
     |  add_note(...)
     |      Exception.add_note(note) --
     |      add a note to the exception
     |
     |  with_traceback(...)
     |      Exception.with_traceback(tb) --
     |      set self.__traceback__ to tb and return self.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from builtins.BaseException:
     |
     |  __cause__
     |      exception cause
     |
     |  __context__
     |      exception context
     |
     |  __dict__
     |
     |  __suppress_context__
     |
     |  __traceback__
     |
     |  args

FUNCTIONS
    Series(data, key='id', value='value', name=None)
        Convert a list-like to a pandas Series object. This core function is
        called by several dimension-specific implementation functions.

        Arguments:
            data:       an object array, generator, or function that returns a list-like

            key:        field for the Series index

            value:      field for the Series column values

            name:       Series column name. If None, same as value

        Returns:
            a pandas Series object

        Example:
            Generally you are better off calling the Series function for a specific feature
            e.g., wbgapi.time.Series(). Direct calls should only be necessary for databases
            with custom dimensions, for instance:

            wbgapi.Series(wbgapi.source.features('version', db=57))

    abbreviate(text, q=None, padding=80)
        Returns a shortened version of the text string comprised of the search pattern
        and a specified number of characters on either side. This is used to optimize
        search results. If the search pattern

    fetch(url, params={}, concepts=False, lang=None)
        Iterate over an API request with automatic paging.  The API returns a
        variety of response structures depending on the endpoint. fetch() sniffs
        the response structure and return the most appropriate set of iterated objects.

        Arguments:
            url:        partial URL (minus the base URL and langage) for the API query, minus the query string

            params:     optional query string parameters (required defaults are supplied by the function)

            concepts:   pass True to return results at the concept level, as opposed to the element/variable level

            lang:       preferred language. Pass none to use the global default

        Returns:
            a generator object.

        Example:
            for row in wbgapi.data.fetch('countries'):
              print(row['id'], row['name'])

        Notes:
            For most use cases there are higher level functions that are easier and safer than
            calling fetch() directly. But it's still very useful for direct testing and discovery
            of the API.

    get(url, params={}, concepts=False, lang=None)
        Return a single response from the API

        Arguments:
            url:        full URL for the API query, minus the query string

            params:     optional query string parameters (required defaults are supplied by the function)

            concepts:   pass True to return a result at the concept level, as opposed to the element/variable level

        Returns:
            First row from the response

        Example:
            print(wbgapi.get('countries/BRA')['name'])

    htmlTable(*args, **kwargs)
        Generates an HTML table wrapped in a <div class="wbgapi"/> to allow users
        to customize the display if they wish. All arguments are passed to tabulate;
        you should not include the 'tablefmt=html' parameter

    metadata(url, variables, concepts='all', **kwargs)
        Return metadata records

        Arguments:
            url:        url with tokens, as per refetch()

            variables:  variables that can be chunked, in priority order (see refetch)

            concepts:   Name or list-like of the concepts to return: 'all' for all concepts

            **kwargs:   Remaining arguments to pass to refetch (must include varables for tokens in url)

        Returns:
            a generator that returns Metadata objects

        Example:
            for meta in wbgapi.metadata('sources/2/series/{series}/country/{economy}/metadata', ['series', 'economy'],
                concepts=['Series','Country-Series'], series='SP.POP.TOTL', economy='FRA;CAN'):
                    print(meta.concept, meta.id, len(meta.metadata))

        Notes:
            Each return from the generator will include a unique concept/id pair and a complete corresponding metadata record

    queryParam(arg, concept=None, db=None)
        Prepare parameters for an API query. This is a core function
        called by several dimension-specific functions of the same name

        Arguments:
            arg:        a record identifier or list-like of identifiers

            concept:    concept for the arguments passed

            db:         database; pass None to access the global database

        Returns:
            a semicolon separated API-ready parameter string

    reduce(...)
        reduce(function, iterable[, initial]) -> value

        Apply a function of two arguments cumulatively to the items of a sequence
        or iterable, from left to right, so as to reduce the iterable to a single
        value.  For example, reduce(lambda x, y: x+y, [1, 2, 3, 4, 5]) calculates
        ((((1+2)+3)+4)+5).  If initial is present, it is placed before the items
        of the iterable in the calculation, and serves as a default when the
        iterable is empty.

    refetch(url, variables, **kwargs)
        repeating fetch: provides a variation of fetch() that allows URLs that exceed the maximium API limit to
        be chunked.

        Arguments:
            url:            partial URL with tokens, each of which must have values specified as function arguments. See example below

            variables:      array of variables to be chunked if necessary, in the order they should be chunked

            **kwargs:       remaining arguments MUST include values for each token in the url string. All arguments to fetch
                            are also acceptable and are passed to fetch. Any "chunkable" variable should be a semicolon-separated
                            value array. Arrays and iterables are not acceptable values


In [ ]:
wb.series.info()

In [ ]:
for row in wb.data.fetch('SP.POP.TOTL', 'USA'): # all years
    print(row)

In [6]:
wb.data.DataFrame(['NY.GDP.PCAP.CD', 'SP.POP.TOTL'], 'CAN', mrv=5)

,YR2017,YR2018,YR2019,YR2020,YR2021
series,,,,,
NY.GDP.PCAP.CD,4.512943e+04,4.654864e+04,4.632867e+04,4.325826e+04,5.198794e+04
SP.POP.TOTL,3.654524e+07,3.706508e+07,3.760123e+07,3.803720e+07,3.824611e+07

In [7]:
help(wb.data.DataFrame)

Help on function DataFrame in module wbgapi.data:

DataFrame(series, economy='all', time='all', index=None, columns=None, mrv=None, mrnev=None, skipBlanks=False, labels=False, skipAggs=False, numericTimeKeys=False, timeColumns=False, params={}, db=None, **dimensions)
    Retrieve a 2-dimensional pandas dataframe.

    Arguments:
        series:             a series identifier or list-like, e.g., SP.POP.TOTL

        economy:            an economy identifier or list-like, e.g., 'BRA' or ['USA', 'CAN', 'MEX']

        time:               a time identifier or list-like, e.g., 'YR2015' or range(2010,2020).
                            Both element keys and values are acceptable

        index:              name or list of dimensions for the DataFrame's index, e.g., 'economy'. If None then the function
                            will define the index based on your request. Note: to get a dataframe with no index
                            (i.e., 0-based integers) call `reset_index()` with on the return value of this function.

        columns:            name of the dimension for the DataFrame's columns, e.g., 'series'. If None then the function
                            will define columns based on your request.

        mrv:                return only the specified number of most recent values (same time period for all economies)

        mrnev:              return only the specified number of non-empty most recent values (time period varies)

        skipBlanks:         skip empty observations

        labels:             include the dimension name for rows

        skipAggs:           skip aggregates

        numericTimeKeys:    store the time object by value (e.g., 2014) instead of key ('YR2014') if value is numeric

        timeColumns:        add extra columns to show the time dimension for each series/economy
                            If 'auto' then the function will guess based on other parameters

        params:             extra query parameters to pass to the API

        dimensions:         extra dimensions, database specific (e.g., version)

    Returns:
        a pandas DataFrame

    Examples:
        # 5 years of population data (with economy names)
        wbgapi.data.DataFrame('SP.POP.TOTL', time=range(2010,2020),labels=True)

        # Most recent poverty and income data for LAC
        wbgapi.data.DataFrame(['SI.POV.NAHC', 'NY.GDP.PCAP.CD'], economy=wb.region.members('LAC'),mrnev=1,timeColumns=True)

        # Fetch most recent CO2 emissions for each country and merge its income group
        wbgapi.data.DataFrame('EN.ATM.CO2E.PC',mrnev=1).join(wbgapi.economy.DataFrame()['incomeLevel'])

        # Top 10 emitters per capita
        wbgapi.data.DataFrame('EN.ATM.CO2E.PC',mrnev=1,labels=True).sort_values('EN.ATM.CO2E.PC',ascending=False).head(10)

    Notes:
        timeColumns currently defaults to False so that the default column composition is consistent. This may change to 'auto'
        at some point, so that mrv behavior is more intuitive for data discovery

In [11]:
wb.data.DataFrame('NY.GDP.PCAP.CD', ['KOR', 'USA', 'JPN', 'FRA', 'GBR'], time = range(1960, 2022)).transpose()

economy           FRA           GBR           JPN           KOR           USA
YR1960    1333.881573   1397.594803    475.319076    158.274637   3007.123445
YR1961    1430.434624   1472.385714    568.907743     93.831759   3066.562869
YR1962    1585.735311   1525.775853    639.640785    106.160111   3243.843078
YR1963    1758.856659   1613.456884    724.693762    146.303055   3374.515171
YR1964    1928.999402   1748.288118    843.616879    123.606837   3573.941185
...               ...           ...           ...           ...           ...
YR2017   38781.049487  40621.334479  38834.052934  31616.843400  59907.754261
YR2018   41557.854859  43306.308305  39727.116600  33436.923065  62823.309438
YR2019   40494.898294  42747.080460  40458.001876  31902.416905  65120.394663
YR2020   39055.282928  40318.557566  39918.167558  31721.298914  63530.633484
YR2021   43658.978978  46510.282782  39312.660373  34997.781643  70248.629000

[62 rows x 5 columns]

In [26]:
wb.economy.info(['CAN', 'USA', 'MEX'])     # Countries in North America

id    value          region    incomeLevel
----  -------------  --------  -------------
CAN   Canada         NAC       HIC
MEX   Mexico         LCN       UMC
USA   United States  NAC       HIC
      3 elements

In [27]:
wb.region.info()

code    name
------  -----------------------------------------------------
AFE     Africa Eastern and Southern
AFR     Africa
AFW     Africa Western and Central
ARB     Arab World
CAA     Sub-Saharan Africa (IFC classification)
CEA     East Asia and the Pacific (IFC classification)
CEB     Central Europe and the Baltics
CEU     Europe and Central Asia (IFC classification)
CLA     Latin America and the Caribbean (IFC classification)
CME     Middle East and North Africa (IFC classification)
CSA     South Asia (IFC classification)
CSS     Caribbean small states
EAP     East Asia & Pacific (excluding high income)
EAR     Early-demographic dividend
EAS     East Asia & Pacific
ECA     Europe & Central Asia (excluding high income)
ECS     Europe & Central Asia
EMU     Euro area
EUU     European Union
FCS     Fragile and conflict affected situations
HPC     Heavily indebted poor countries (HIPC)
LAC     Latin America & Caribbean (excluding high income)
LCN     Latin America & Caribbean
LDC     Least developed countries: UN classification
LTE     Late-demographic dividend
MDE     Middle East (developing only)
MEA     Middle East & North Africa
MNA     Middle East & North Africa (excluding high income)
NAC     North America
NAF     North Africa
NRS     Non-resource rich Sub-Saharan Africa countries
OED     OECD members
OSS     Other small states
PRE     Pre-demographic dividend
PSS     Pacific island small states
PST     Post-demographic dividend
RRS     Resource rich Sub-Saharan Africa countries
SAS     South Asia
SSA     Sub-Saharan Africa (excluding high income)
SSF     Sub-Saharan Africa
SST     Small states
SXZ     Sub-Saharan Africa excluding South Africa
WLD     World
XZN     Sub-Saharan Africa excluding South Africa and Nigeria
        44 elements

In [33]:
list(wb.source.Series())

['Doing Business',
 'World Development Indicators',
 'Worldwide Governance Indicators',
 'Subnational Malnutrition Database',
 'International Debt Statistics',
 'Africa Development Indicators',
 'Education Statistics',
 'Enterprise Surveys',
 'Gender Statistics',
 'Global Economic Monitor',
 'Health Nutrition and Population Statistics',
 'IDA Results Measurement System',
 'Millennium Development Goals',
 'Quarterly Public Sector Debt',
 'Quarterly External Debt Statistics SDDS',
 'Quarterly External Debt Statistics GDDS',
 'Jobs',
 'Global Economic Prospects',
 'Global Financial Inclusion',
 'The Atlas of Social Protection: Indicators of Resilience and Equity',
 'Exporter Dynamics Database – Indicators at Country-Year Level',
 'Country Policy and Institutional Assessment',
 'Global Financial Development',
 'G20 Financial Inclusion Indicators',
 'Global Partnership for Education',
 'Sustainable Energy for All',
 'Statistical Capacity Indicators',
 'LAC Equity Lab',
 'Subnational Poverty',
 'Health Nutrition and Population Statistics by Wealth Quintile',
 'Population estimates and projections',
 'Country Partnership Strategy for India (FY2013 - 17)',
 'Adjusted Net Savings',
 'Indonesia Database for Policy and Economic Research',
 'Sustainable Development Goals ',
 'Subnational Population',
 'Joint External Debt Hub',
 'WDI Database Archives',
 'Universal Health Coverage',
 'Wealth Accounts',
 'Economic Fitness',
 'PPPs Regulatory Quality',
 'International Comparison Program (ICP) 2011',
 'Human Capital Index',
 'Worldwide Bureaucracy Indicators',
 'Health Equity and Financial Protection Indicators',
 'Logistics Performance Index',
 'PEFA 2011',
 'PEFA 2016',
 'Global Financial Inclusion and Consumer Protection Survey',
 'Economic Fitness 2',
 'International Comparison Program (ICP) 2005',
 'Global Financial Inclusion and Consumer Protection Survey (Internal)',
 'Environment, Social and Governance (ESG) Data',
 'Remittance Prices Worldwide (Sending Countries)',
 'Remittance Prices Worldwide (Receiving Countries)',
 'ICP 2017',
 'PEFA_GRPFM',
 'Gender Disaggregated Labor Database (GDLD)',
 ' International Debt Statistics: DSSI',
 'Global Public Procurement',
 'Statistical Performance Indicators (SPI)',
 'Education Policy',
 'PEFA_2021_SNG',
 'Global Jobs Indicators Database (JOIN)',
 'Country Climate and Development Report (CCDR)',
 'Food Prices for Nutrition',
 'Identification for Development (ID4D) Data']