In [1]:
import pandas as pd
import numpy as np
import datetime as dt

# 시계열 데이터 생성

사용자는 python에서 제공하는 날짜와 시간 데이터 타입과 클래스를 인덱스로 설정하고 이와 연관된 데이터를 입력하여 시계열 데이터를 직접 만들 수 있다. 하지만 요즘같은 세상에 그런 데이터를 하나 하나 입력하여 생성한다는 것은 매우 비효율적인 방법임에 틀림없다. 특히 요즘같이 빅데이터를 다루는 시기에 데이터를 직접 입력해서 만드는 것은 상상도 할 수 없는 일이고, 만약 그렇게 만들 수 있다고 해도 간단한 테스트용이나 1회성 데이터일 것이다. 따라서 대부분의 시계열 데이터는 대량의 데이터가 기록된 데이터베이스, 파일 등에서 추출하여 임포트하는 것이 일반적이다. 또 하나의 방법은 다양한 기관이나 웹에서 공식적으로 제공하는 API를 사용하거나 python에서 제공하는 웹 데이터베이스 접근 라이브러리를 사용하여 데이터를 가져올수도 있다. 

이번 장에서는 이 책 전반에서 사용할 시계열 데이터 세트를 만들기 위해 월드뱅크에서 제공하는 웹 데이터베이스에 접근하는 라이브러리를 사용하는 데이터 추출 방법과 엑셀과 CSV 파일을 사용해 데이터를 추출하는 하는 방법을 사용하여 시계열 데이터를 생성하는 방법에 대해 설명한다.

## 데이터 스크래핑 라이브러리

python에서 인터넷과 웹에서 공개된 데이터를 가져오는 라이브러리를 웹 스크래핑(Web Scraping) 라이브러리 혹은 데이터 스크래핑 라이브러리라고 한다. 이 스크래핑 라이브러리는 인터넷에 게시된 html, xml, json 파일을 읽어 불러들이거나 데이터베이스 보유 사이트에서 제공하는 API를 통해 데이터를 불러들이는 기능을 제공한다. 인터넷에 게시된 html, xml, json 등의 데이터를 불러들이는 라이브러리는 매개변수로 전달된 해당 데이터가 게시된 사이트와 데이터 형식을 사용해 해당 데이터를 읽어들이기 때문에 사용 범위가 매우 넓고 다양한 소스의 데이터를 엑세스 할 수 있다는 점에서 장점이 있다. 하지만 웹에 게시된 형태로 데이터를 다운로드 받기 때문에 표준화 되어 있지 않은 경우가 많아 데이터를 불러들인 후 후처리 작업이 필요다는 단점이 있다. 특히 과도한 스크래핑은 자칫 해당 작업이 블로킹 되는 경우도 있어 주의가 필요하다.  반면 데이터베이스 보유 사이트에서 제공하는 API를 사용하는 라이브러리는 미리 표준화된 데이터를 다운로드 받기 때문에 후처리에 드는 노력이 비교적 적고 데이터 갱신에 대한 오류 발생 가능성이 적다는 장점이 있지만 해당 API의 접근 권한을 미리 받아야 하는 경우가 많고 사용자가 제공하는 데이터에 한정된다는 단점이 있다. 

웹에 게시된 데이터를 스크래핑하는데 많이 사용되는 python 라이브러리는 다음과 같다. 

- requests : html 문서를 가져올 때 사용하는 패키지로써, 웹 크롤링이나 웹 스크래핑에 매우 많이 사용되는 python 라이브러리이다. HTML 문서를 파싱하고 CSS 선택자를 이용하여 웹 문서에서 데이터를 추출하여 사용할 수 있는데, requests.get(), requests.post(), requests.put(), requests.delete()와 같이  html 문서를 작성하는데 사용하는 문법과 유사한 문법을 사용함으로서 다루기가 쉽다는 장점이 있다. 

- Selenium : 브라우저 자동화 도구로, 동적 웹 페이지에서 데이터를 스크래핑하는 데에 주로 사용되는 라이브러리이다. 

- Beautiful Soup: HTML과 XML 문서를 파싱하고 데이터를 추출하기 위한 라이브러리이다.

- urllib: URL을 다루는 라이브러리로써, HTTP 요청을 보내는 데에 사용된다.

- Scrapy: 대규모 웹 스크래핑에 적합한 라이브러리로, 분산 스크래핑과 스크래핑한 데이터를 처리하는 기능을 제공한다.
 
또한 API를 사용하여 데이터를 스크래핑하는데 많이 사용되는 python라이브러리는 다음과 같다. 

- pandas_datareader: pandas_datareader는 다양한 웹 데이터 소스에서 데이터를 가져오는 pandas의 서브 라이브러리로 World Bank, OECD, FRED와 같은 글로벌 데이터 소스의 API 방식을 지원한다.

- pandas-gbq: pandas-gbq는 Google BigQuery에서 데이터를 가져오는 pandas의 서브 라이브러리이다.

- quandl: 많은 해외 국가의 금융 데이터를 제공하는 데이터 마켓인 https://data.nasdaq.com/에서 제공하는 API를 사용하여 데이터를 가져오는 라이브러리이다. 세계 각국 주식 시장의 주식 가격, 환율, 기타 금융 데이터가 제공된다.

- alpha_vantage: https://www.alphavantage.co/에서 제공하는 다양한 금융 데이터를 가져오는 라이브러리로, 암호화폐, 주식, 환율 등을 지원한다.

- yfinance: Yahoo Finance에서 제공하는 주식 가격 데이터를 가져오는 라이브러리이다.

- covid19py: COVID-19에 대한 데이터를 가져오는 라이브러리로 Johns Hopkins University와 WHO(Wolrd Health Organization)에서 공식적으로 공표하는 데이터를 지원한다.

- IMDbPY: 인터넷 영화 데이터베이스인 IMDb의 데이터를 가져올 수 있는 라이브러리로써, 영화 정보, 출연 배우 정보 등 다양한 데이터를 가져올 수 있다.

이 외에도 많은 파이썬 라이브러리들이 다양한 데이터를 가져오는 데 사용되는데 이번 장에서는 World bank 데이터를 가져오는 방법을 알아본다. 

월드 뱅크는 빈곤 해소를 목적으로 세계은행(世界銀行)은 유엔 산하의 국제 금융기관이다. 월드 뱅크에서는 전세계 여러 나라의 경제 지표를 비롯하여 교육, 기후변화, 환경, 노동, 건강 등의 20여개 이상의 분야에 걸친 2000여개 이상의 다양한 사회 지표를 제공하고 있다. 월드 뱅크 홈페이지를 통해 직접 지표를 검색하여 그래프를 사용하거나 해당 데이터를 엑셀, CSV 파일등으 다운로드 검색 방식 외에도 국가별 자료를 확인할 수도 있고 주제별로 모아진 지표를 한꺼번에 확인하고 필요한 지표를 선택하여 조회하거나, 해당 데이터를 CSV, XML, Excel 파일로 다운로드할 수 있다. 또 월드 뱅크에서 제공하는 API를 사용하여 해당 데이터를 바로 pandas 데이터프레임으로 가져올 수도 있다. 

월드 뱅크 데이터를 가져오는 방식은 여러가지가 있으나 여기서는 월드 


WBGAPI는 World Bank의 데이터 API에 대한 최신 Python 액세스를 제공합니다. 데이터 초보자와 데이터 과학자 유형 모두를 위해 설계되었습니다.

WBGAPI는 몇 가지 측면에서 세계 은행 데이터에 대한 다른 패키지와 다르며 일반적으로 세계 은행의 강력한 API를 최대한 활용하면서 일부 이념의 영향을 완화하려고 합니다. 다른 패키지와 가장 중요한 차이점은 WBGAPI가 데이터베이스를 집합적으로가 아니라 개별적으로 쿼리한다는 것입니다. 기본적으로 WBGAPI는 World Development Indicators 데이터베이스(db=2)를 쿼리하지만 각 요청에 대해 또는 전역적으로 기본값을 변경할 수 있습니다. 이렇게 하면 인구(SP.POP.TOTL)와 같은 지표가 여러 다른 데이터베이스에 나타나거나 다른 데이터베이스의 차원, 경제 또는 기간이 다른 경우 혼동을 방지할 수 있습니다.

In [2]:
from pandas_datareader import wb

matches = wb.search('gdp.*capita.*const')
dat = wb.download(indicator='NY.GDP.PCAP.KD', country=['US', 'CA', 'MX'], start=2005, end=2008)
print(dat)

SSLError: HTTPSConnectionPool(host='api.worldbank.org', port=443): Max retries exceeded with url: /v2/indicators?per_page=50000&format=json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))

In [2]:
import wbgapi as wb
df_GDP = wb.data.DataFrame(['NY.GDP.MKTP.CD'], ['KOR', 'USA', 'FRA', 'JPN', 'GBR', 'DEU', 'ITA', 'CAN', 'EUU', 'OED', 'WLD'])

In [3]:
df_GDP = df_GDP.transpose().reset_index()
df_GDP.rename(columns={'index': 'year'}, inplace=True)

In [4]:
df_GDP['year'] = pd.to_datetime(df_GDP['year'].str.replace('YR', ''))

In [5]:
df_GDP = df_GDP.set_index('year')

In [6]:
df_GDP.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 62 entries, 1960-01-01 to 2021-01-01
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CAN     62 non-null     float64
 1   DEU     52 non-null     float64
 2   EUU     52 non-null     float64
 3   FRA     62 non-null     float64
 4   GBR     62 non-null     float64
 5   ITA     62 non-null     float64
 6   JPN     62 non-null     float64
 7   KOR     62 non-null     float64
 8   OED     62 non-null     float64
 9   USA     62 non-null     float64
 10  WLD     62 non-null     float64
dtypes: float64(11)
memory usage: 5.8 KB

In [7]:
df_GDP.loc['2015':'2021']

economy,CAN,DEU,EUU,FRA,GBR,ITA,JPN,KOR,OED,USA,WLD
year,,,,,,,,,,,
2015-01-01,1.556509e+12,3.357586e+12,1.355251e+13,2.439189e+12,2.934858e+12,1.836638e+12,4.444931e+12,1.465773e+12,4.740883e+13,1.820602e+13,7.518784e+13
2016-01-01,1.527995e+12,3.469853e+12,1.388901e+13,2.472964e+12,2.699660e+12,1.877072e+12,5.003678e+12,1.500112e+12,4.832536e+13,1.869511e+13,7.646155e+13
2017-01-01,1.649266e+12,3.690849e+12,1.476492e+13,2.595151e+12,2.683399e+12,1.961796e+12,4.930837e+12,1.623901e+12,5.044393e+13,1.947734e+13,8.140067e+13
2018-01-01,1.725329e+12,3.974443e+12,1.598083e+13,2.790957e+12,2.878152e+12,2.091932e+12,5.037835e+12,1.724846e+12,5.336583e+13,2.053306e+13,8.645689e+13
2019-01-01,1.742015e+12,3.888226e+12,1.569340e+13,2.728870e+12,2.857058e+12,2.011302e+12,5.123318e+12,1.651423e+12,5.387859e+13,2.138098e+13,8.764526e+13
2020-01-01,1.645423e+12,3.889669e+12,1.536944e+13,2.639009e+12,2.704609e+12,1.896755e+12,5.040108e+12,1.644313e+12,5.251705e+13,2.106047e+13,8.510560e+13
2021-01-01,1.988336e+12,4.259935e+12,1.717742e+13,2.957880e+12,3.131378e+12,2.107703e+12,4.940878e+12,1.810956e+12,5.826835e+13,2.331508e+13,9.651308e+13

# 월 주기 시계열 데이터

In [8]:
df_import = pd.read_excel('./국가별_수출입현황_20230218214213.xlsx')

In [9]:
df_import['항목'] = df_import['항목'].str.strip("(천불) ")
df_import.rename(columns={'국가별(1)': 'nation', '항목':'div'}, inplace=True)

In [10]:
df_import = df_import.set_index(['nation', 'div']).transpose()

In [11]:
df_import.index = pd.to_datetime(df_import.index)

In [12]:
df_import

nation            중국                          미국                         일본  \
div             수출금액      수입금액     무역수지     수출금액     수입금액     무역수지     수출금액
2000-01-01   1235215   1008166   227050  2609788  2217025   392763  1551722
2000-02-01   1273117    834291   438827  2554310  2241520   312790  1518845
2000-03-01   1437377   1125348   312029  2946821  2607380   339441  1783565
2000-04-01   1366877   1032362   334514  2698030  2570158   127872  1582708
2000-05-01   1663241   1066610   596630  3167181  2634243   532939  1671040
...              ...       ...      ...      ...      ...      ...      ...
2022-08-01  13115471  13501725  -386254  8751789  7778957   972832  2547188
2022-09-01  13340884  12677935   662949  9248935  6657650  2591284  2581532
2022-10-01  12157489  13411886 -1254397  8600832  6692725  1908107  2272232
2022-11-01  11376108  12129628  -753520  8779500  6528281  2251219  2310412
2022-12-01  11185579  11805167  -619588  9373382  6789361  2584020  2434500

nation                             홍콩  ...     싱가포르       인도                   \
div            수입금액     무역수지     수출금액  ...     무역수지     수출금액    수입금액     무역수지
2000-01-01  2357231  -805509   782349  ...   145743   126874   74035    52839
2000-02-01  2430091  -911246   823990  ...   114522   144711   62395    82316
2000-03-01  2935699 -1152135   911648  ...   246557   143327   84936    58390
2000-04-01  2814895 -1232187   863243  ...   134400   100741   91855     8886
2000-05-01  2627642  -956602   887081  ...   206414   106458   82600    23858
...             ...      ...      ...  ...      ...      ...     ...      ...
2022-08-01  4462855 -1915668  1949329  ...  1183170  1630558  682116   948442
2022-09-01  4434724 -1853192  2873737  ...  1098691  1614997  579052  1035944
2022-10-01  4300357 -2028126  2006525  ...   529239  1403342  521838   881504
2022-11-01  4313148 -2002736  1812631  ...   549070  1380207  537473   842734
2022-12-01  4479914 -2045414  1815664  ...   513669  1489874  497528   992346

nation          독일                        멕시코
div           수출금액     수입금액     무역수지     수출금액    수입금액    무역수지
2000-01-01  334996   380841   -45845   174354   52682  121671
2000-02-01  277001   330405   -53404   158955   29094  129861
2000-03-01  369061   463624   -94563   185639   24452  161187
2000-04-01  402004   364715    37289   183799   30489  153310
2000-05-01  445961   391222    54740   200054   22360  177694
...            ...      ...      ...      ...     ...     ...
2022-08-01  803647  2066739 -1263092  1103795  706052  397743
2022-09-01  942270  1630175  -687906   991606  672527  319079
2022-10-01  723320  2113019 -1389699   875039  730601  144437
2022-11-01  647809  2005967 -1358157   857672  660770  196901
2022-12-01  919825  2140391 -1220566   925482  882439   43042

[276 rows x 30 columns]

In [13]:
df_import.loc['2022', ('중국', '수출금액')]

2022-01-01    13370137
2022-02-01    13041060
2022-03-01    15642409
2022-04-01    12948986
2022-05-01    13422068
2022-06-01    12960598
2022-07-01    13216887
2022-08-01    13115471
2022-09-01    13340884
2022-10-01    12157489
2022-11-01    11376108
2022-12-01    11185579
Name: (중국, 수출금액), dtype: int64

# 일 주기 시계열 데이터

In [14]:
df_gold = pd.read_csv('./gold.csv', parse_dates = ['Date'], index_col = 'Date')

In [15]:
df_gold.loc['2022-01-25':'2022-01-30']

              Open    High     Low   Close  Volume Currency
Date
2022-01-25  1843.6  1854.2  1834.4  1852.5  197804      USD
2022-01-26  1848.0  1850.2  1814.1  1829.7  270028      USD
2022-01-27  1819.0  1821.4  1790.6  1793.1  196036      USD
2022-01-28  1799.6  1800.3  1780.6  1786.6  217149      USD